use_frameworks!

platform :ios, '10.0'

target 'SYCollectionViewRoundFlowLayout_Example' do
  pod 'SYCollectionViewRoundFlowLayout', :path => '../'

  target 'SYCollectionViewRoundFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
